[package]
name = "qlog_dancing_baby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
env_logger = "0.10.0"
log = "0.4.17"
qlog = "0.9.0"
serde_json = "1"
serde = "1"

